// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjp-58J6UXWehtTaBE69WJYlmy7gPtrpg',
    appId: '1:1081236797845:web:069e4777ec64a0e8199e9c',
    messagingSenderId: '1081236797845',
    projectId: 'carecommerce-fbdcc',
    authDomain: 'carecommerce-fbdcc.firebaseapp.com',
    storageBucket: 'carecommerce-fbdcc.appspot.com',
    measurementId: 'G-SDFL6ZW9DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE215VmwNlZzS-R9WjDuZjr6YtNVMMCqE',
    appId: '1:1081236797845:android:6adb6cec26b675f1199e9c',
    messagingSenderId: '1081236797845',
    projectId: 'carecommerce-fbdcc',
    storageBucket: 'carecommerce-fbdcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI8pFhNsQhcM-zdQJ01NOAuDLh3CVjoY8',
    appId: '1:1081236797845:ios:6bb4b8b14ac586ff199e9c',
    messagingSenderId: '1081236797845',
    projectId: 'carecommerce-fbdcc',
    storageBucket: 'carecommerce-fbdcc.appspot.com',
    androidClientId: '1081236797845-joi08msgmq27a72aspqu642qm7q8jq45.apps.googleusercontent.com',
    iosClientId: '1081236797845-qqgonevuc4iaub8tu7ghfl2o0670sff1.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfeprojectcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI8pFhNsQhcM-zdQJ01NOAuDLh3CVjoY8',
    appId: '1:1081236797845:ios:6bb4b8b14ac586ff199e9c',
    messagingSenderId: '1081236797845',
    projectId: 'carecommerce-fbdcc',
    storageBucket: 'carecommerce-fbdcc.appspot.com',
    androidClientId: '1081236797845-joi08msgmq27a72aspqu642qm7q8jq45.apps.googleusercontent.com',
    iosClientId: '1081236797845-qqgonevuc4iaub8tu7ghfl2o0670sff1.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfeprojectcar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjp-58J6UXWehtTaBE69WJYlmy7gPtrpg',
    appId: '1:1081236797845:web:b451292d586b9088199e9c',
    messagingSenderId: '1081236797845',
    projectId: 'carecommerce-fbdcc',
    authDomain: 'carecommerce-fbdcc.firebaseapp.com',
    storageBucket: 'carecommerce-fbdcc.appspot.com',
    measurementId: 'G-X950K8QEWK',
  );

}